# Generated by Django 4.2.26 on 2025-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
